Rails/01_address_book/Contactify/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'site#home'

  get "/contacts/search" => 'contacts#search'
  get "/contacts/show_favourites" => 'contacts#show_favourites'
  post "/contacts/favourite" => 'contacts#favourite'
  post "/contacts/del_favourite" => 'contacts#del_favourite'
  resources :contacts, only: [:index, :show, :new, :create, :edit, :update]

end

Rails/01_address_book/Contactify/app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
	validates :address, presence: true
	def to_s
    	[name, address, phone1, phone2, email1, email2].compact.join(" // ")
    end

    def show_name
    	name
    end

    def new
    	@project = Project.new
    end
end

Rails/01_address_book/Contactify/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Rails/01_address_book/Contactify/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index
  	@contacts = Contact.order(name: :asc).limit(15)
  end

  def show
		@contact = Contact.find(params[:id])
	end

	def edit
		@contact = Contact.find(params[:id])
	end

	def new
  	@contact = Contact.new
  end

  def favourite
  	current_contact = Contact.find(params[:id])
  	current_contact.favourite = true
  	current_contact.save
  	redirect_to contacts_path, notice: 'Marked as favourite!'
  end

  def del_favourite
  	current_contact = Contact.find(params[:id])
  	current_contact.favourite = nil
  	current_contact.save
  	redirect_to contacts_path, notice: 'Deleted the favourite!'
  end

  def show_favourites
		@contacts = Contact.where(favourite: true)
		render :show_favourites
	end

	def create
		@contact = Contact.new(contact_params)
		if Contact.find_by(name: params[:contact][:name])
			redirect_to new_contact_path, notice: 'Contact already exists. Please create a new one...'
		elsif @contact.valid?
			@contact.save
			redirect_to contacts_path, notice: 'Contact was successfully created.'
		else
			render :new
		end
	end

	def update
		@contact = Contact.find_by(id: params[:id])
		if @contact.update_attributes(contact_params)
			redirect_to contacts_path, notice: 'Contact was successfully updated.'
		else
			render :edit
		end
	end

	private

	def contact_params
		params.require(:contact).permit(:name, :address, :phone1, :phone2, :email1, :email2)
	end
end

Rails/01_address_book/Contactify/app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
	end
end

Rails/01_address_book/Contactify/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/01_address_book/Contactify/app/helpers/contacts_helper.rb
module ContactsHelper
end

Rails/01_address_book/Contactify/app/helpers/site_helper.rb
module SiteHelper
end

Rails/01_address_book/Contactify/app/views/contacts/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h4>Update this contact</h4>
			<ul>
				<%= form_for(@contact) do |f| %>
				<%= render 'layouts/errors', model: @contact %>
				<li>
					<div class="field">
						<%= f.label :name %>
						<%=f.text_field :name %>
					</div>
				</li>

				<li>
					<div class="field">
					<%= f.label :address %>
					<%=f.text_field :address %>
					</div>
				</li>
				<li>
					<div class="field">
					<%= f.label :phone1 %>
					<%=f.text_field :phone1 %>
				</div></li>

				<li>
					<div class="field">
					<%= f.label :phone2 %>
					<%=f.text_field :phone2 %>
					</div>
				</li>

				<li>
					<div class="field">
					<%= f.label :email1 %>
					<%=f.text_field :email1 %>
					</div>
				</li>

				<li>
					<div class="field">
					<%= f.label :email2 %>
					<%=f.text_field :email2 %>
					</div>
				</li>
			<Ul>
			<ul>
				<li>
					<div class="actions btn">
					<%= f.submit %>
					</div>
				</li>
				<% end %>
			</ul>
		</div>
		<div class="col-md-6">
			<% if @contact.favourite == true %>
				<ul>
					<li>
					<%= form_tag("/contacts/del_favourite", class:"btn") do %>
					<%= hidden_field_tag(:id, @contact.id) %>
					<%= submit_tag("Delete favourite") %>
					<% end %>
					</li>
				</ul>
			<%else %>
				<ul>
					<li>
						<%= form_tag("/contacts/favourite", class:"btn") do %>
							<%= hidden_field_tag(:id, @contact.id) %>
							<%= submit_tag("Mark as favourite") %>
						<%end%>
					</li>
				</ul>
			<%end%>
		</div>
	</div>
</div>

Rails/01_address_book/Contactify/app/views/contacts/edit.html.erb
<h2>Edit Project</h2>

<%= render 'form', project: @project %>

Rails/01_address_book/Contactify/app/views/contacts/index.html.erb
<title>Contactify</title>

<div class="container">
	<div class="row">
		<h2>Find all your contacts here</h2>
		<h3>Click on the contact name to access all the info</h3>
	</div>
	<div class="row">
		<div class="col-md-5">
			<ul>
  			<% @contacts.each do |contact| %>
  				<li><%= link_to contact.name, contact_path(contact) %></li>
					<% if contact.favourite == true %>
						<%= form_tag("/contacts/del_favourite", class:"btn") do %>
						<%= hidden_field_tag(:id, contact.id) %>
						<%= submit_tag("Delete favourite") %>
						<% end %>
					<%else%>
						<%= form_tag("/contacts/favourite", class:"btn") do %>
						<%= hidden_field_tag(:id, contact.id) %>
						<%= submit_tag("Mark as favourite") %>
						<% end %>
					<% end %>
				<%end%>
			</ul>
			<ul>
				<li><b> <%= link_to 'Create a new contact', new_contact_path %></b></li>
			</ul>
		</div>
		<div class="col-md-7">

			<ul>
				<li><b><%= link_to 'Show all your favourites', contacts_show_favourites_path %></b></li>
			</ul>
		</div>
	</div>
</div>

Rails/01_address_book/Contactify/app/views/contacts/new.html.erb
<h2>Add a New Contact to Contactify</h2>

<%= render 'form', contact: @contact %>

Rails/01_address_book/Contactify/app/views/contacts/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="media">
  				<div class="media-left">
    				<a href="#" class="pull-left">
      					<img class="media-object" src="http://38.media.tumblr.com/avatar_f721923ca467_64.png" alt="ProfilePic">
    				</a>
  				</div>
  				<div class="media-body">
    				<h4 class="media-heading"><%= @contact.name %> lives in <%= @contact.address %></h4>
 					Contact information:
 					</br>
 					<span class="glyphicon glyphicon-earphone"></span>
					<%= @contact.phone1 %>
					<%if @contact.phone2.present?%>
						or
						<%= @contact.phone2 %>
					<%end%>
					</br>
					<span class="glyphicon glyphicon-envelope"></span>
					<%= @contact.email1 %>
					<%if @contact.email2.present?%>
						or
						<%= @contact.email2 %>
					<%end%>
  				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<%= render 'form', contact: @contact %>
		</div>
	</div>
</div>

Rails/01_address_book/Contactify/app/views/contacts/show_favourites.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<ul>
				<% if @contacts.present? %>
				<h3>The favourite contacts you have are:</h3>
					<% @contacts.each do |contact| %>
						<div class="media">
			  				<div class="media-left">
			    				<a href="#" class="pull-left">
			      					<img class="media-object" src="http://38.media.tumblr.com/avatar_f721923ca467_64.png" alt="ProfilePic">
			    				</a>
			  				</div>
			  				<div class="media-body">
			    				<h4 class="media-heading"><%= contact.name %> lives in <%= contact.address %></h4>
			 					Contact information:
			 					</br>
			 					<span class="glyphicon glyphicon-earphone"></span>
								<%= contact.phone1 %>
								<%if contact.phone2.present?%>
									or
									<%= contact.phone2 %>
								<%end%>
								</br>
								<span class="glyphicon glyphicon-envelope"></span>
								<%= contact.email1 %>
								<%if contact.email2.present?%>
									or
									<%= contact.email2 %>
								<%end%>
			  				</div>
						</div>
					<%end%>
				<% else %>
					<h3>Sorry, you couldn't find any contact for this letter.</h3>
				<% end %>
			</ul>

<ul>
<% @contacts.each do |contact| %>
<li> <%= contact.name %>
</li>
<% end %>

Rails/01_address_book/Contactify/app/views/layouts/_errors.html.erb
<% if model.errors.any? %>

	<div class="model errors">	
		<h2> 
			<%= pluralize(model.errors.count, "error") %>
			<%= "prohibited this #{model.class.name} from being saved:" %>
		</h2>

		<ul>
			<% model.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

Rails/01_address_book/Contactify/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contactify</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |key, value| %>
		<%= content_tag :div, value, class: "flash-info" %>
		<% end %>

	<div class="page-header">
  		<h1>Contactify <small>All your contacts in one place</small></h1>
	</div>
	<%= yield %>
	<footer>
		<ul>
			<li><%= link_to "All your contacts", contacts_path %> </li>
			<li>Powered by Ruby on Rails <a href="http://bbrassart.com/">@bbrassart</a></li>
		</ul>
	</footer>
</body>
</html>

Rails/01_address_book/Contactify/app/views/site/home.html.erb
<h1> Welcome to Contactify homepage </h1>
<p> IronHack powered </p> 