API/bbq_planner/bbq_planner/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'barbecues#index'
  namespace :api do
    namespace :v1 do
      get 'barbecues' => 'barbecues#show_all'
      get 'barbecues/:id' => 'barbecues#show_bbq'
      post 'barbecues/join' => 'barbecues#join_bbq'
      post 'barbecues/item/' => 'barbecues#additem'
    end
  end

  resources :barbecues, only: [ :index, :new, :create ]
end

API/bbq_planner/bbq_planner/app/models/barbecue.rb
class Barbecue < ActiveRecord::Base
  validates :title, presence: true
  validates :venue, presence: true
  validates :date, presence: true
  has_and_belongs_to_many :users
  has_many :items
end

API/bbq_planner/bbq_planner/app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :barbecue
end

API/bbq_planner/bbq_planner/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :barbecue


end

API/bbq_planner/bbq_planner/app/controllers/api/v1/barbecues_controller.rb
class Api::V1::BarbecuesController < ApplicationController

  def show_all
   barbecues = Barbecue.all
   attended_barbecues = [];
   unattended_barbecues = [];
   barbecues.each do |bbq|
     if bbq.users.include?(current_user)
       attended_barbecues << bbq
     else
       unattended_barbecues << bbq
     end
   end
   render json: {:attended_barbecues => attended_barbecues, :unattended_barbecues => unattended_barbecues};
  end

  def join_bbq
    id = params[:id]
    barbecue = Barbecue.find(id)
    unless barbecue.users.include?(current_user)
      barbecue.users << current_user
      barbecue.save
    end
    render :json => 'ok'
  end

  def additem
    user_product = params[:value]
    barbecue = Barbecue.find(params[:bbq])
    barbecue.items.new(product: user_product)
    if barbecue.users.include?(current_user)
      barbecue.save
    end
  end

  def show_bbq
    id = params[:id]
    barbecue = Barbecue.find(id)
    users = barbecue.users
    items = barbecue.items
    participating = false
    if users.include?(current_user)
      participating = true
    end
    render json: {:participating => participating, :barbecue => barbecue, :users => users, items: items}
  end
end

API/bbq_planner/bbq_planner/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

API/bbq_planner/bbq_planner/app/controllers/barbecues_controller.rb
class BarbecuesController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def new
    @bbq = Barbecue.new
  end

  def create
    bbq_params = params.require(:barbecue).permit(:title, :venue, :date)
    @bbq = Barbecue.new(bbq_params)

    unless @bbq.save
      render(:new)
    else
      redirect_to(barbecues_path)
    end
  end
end

API/bbq_planner/bbq_planner/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

end

API/bbq_planner/bbq_planner/app/helpers/barbecues_helper.rb
module BarbecuesHelper
  def format_date(date)
    return date.strftime('%B, %e %Y at %l:%M %P')
  end
end

API/bbq_planner/bbq_planner/app/views/barbecues/index.html.erb
<h1>BBQs</h1>

<div>
  <a href="<%= new_barbecue_path %>" class="btn btn-primary">
    Add a new BBQ
  </a>
</div>
<div>
  <p>Click here to see all the barbecues</p>
  <button class="btn btn-primary" id="showAll">Show all</button>
</div>
<div id="main">

</div>
<div id="addNewItem"></div>

API/bbq_planner/bbq_planner/app/views/barbecues/new.html.erb
<h1>Add a new BBQ</h1>

<% if @bbq.errors.any? %>
  <ul class="list-unstyled">
    <% @bbq.errors.full_messages.each do |msg| %>
      <li class="alert alert-danger" role="alert"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @bbq do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :venue %>
    <%= form.text_field :venue, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.date_field :date, class: 'form-control' %>
  </div>

  <button type="submit" class="btn btn-success">
    Add BBQ
  </button>
<% end %>

API/bbq_planner/bbq_planner/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Barbecues</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', defer: true %>
  <%= csrf_meta_tags %>
</head>
<body data-hook="controller-<%= controller_name %> action-<%= action_name %>">

  <div class="container">
    <div id="top_bar">
      <% if user_signed_in? %>
        <span><%= current_user.email %></span>
        <span><%= link_to 'Sign out', destroy_user_session_path, method: 'DELETE' %></span>
      <% else %>
        <span>
          <%= link_to 'Sign_up', new_user_registration_path %> |
          <%= link_to 'Sign_in', new_user_session_path %>
        </span>
      <% end %>
    </div>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>