Rails/03_MusicConcertNetwork/MeetMusic/config/routes.rb
Rails.application.routes.draw do

  get '/' => 'site#home'
  post'/concerts/:concert_id' => 'comments#create'
  get '/concerts/mostpopular' => 'comments#mostpopular'

  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  get '/logout' => "sessions#destroy"



  resources :concerts, only: [:index, :show, :create, :new, :edit, :update, :destroy] do
    resources :comments, only: [:index, :show, :create, :new, :edit, :destroy]
    end

  resources :users, only: [:new, :create]


 get '/concerts/mostpopular' => 'comments#mostpopular'

end

Rails/03_MusicConcertNetwork/MeetMusic/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :concert

 	validates :message, presence: true
end

Rails/03_MusicConcertNetwork/MeetMusic/app/models/concert.rb
class Concert < ActiveRecord::Base
	has_attached_file :logo, styles: {:medium => "300x300", :thumb => "100x100"}
	validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\z/
	validates :band, presence: true
	validates :venue, presence: true
	validates :city, presence: true	
	validates :date, presence: true
	validates :price, presence: true
	validates :description, presence: true
	has_many :comments, dependent: :destroy
	accepts_nested_attributes_for :comments

	def self.fetch(date = Date.current)
		Concert.order(:date)
	end

	def to_s()
		[name, email].compact.join(" // ")
	end
end

Rails/03_MusicConcertNetwork/MeetMusic/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    unless self.roles
      self.roles = :user
    end
  end
end

Rails/03_MusicConcertNetwork/MeetMusic/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if @current_user.nil?
      @current_user = User.find_by_id(session[:user_id])
    end
    @current_user
  end

  def admin_only
    if not (current_user && current_user.roles=='admin')
      flash[:acces_denied] = "Acces denied. You must be admin to see this page"
      redirect_to concerts_path
    end

  end  
end

Rails/03_MusicConcertNetwork/MeetMusic/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		@concert = Concert.find(params[:concert_id])
		@comment = Comment.new(:concert=>@concert)
	end

	def create
		@concert = Concert.find(params[:concert_id])
		@comment = @concert.comments.new comment_params
		@comment.visitor = current_user.name
		if @comment.save
			redirect_to concert_path(@concert), notice: 'Your comment has been submitted'
		else
			render :new
		end
	end

	def destroy
		@concert = Concert.find(params[:concert_id])
		@comment = Comment.find_by(id: params[:id]).try(:destroy)
		redirect_to concert_path(@concert), notice: "The comment has been destroyed."
	end

	def mostpopular
		concerts = Concert.all
		temp = concerts.sort { |a,b| b.comments.length <=> a.comments.length} 
		@most_popular_concerts = temp[0..3]
	end

	private
	def comment_params
		params.require(:comment).permit(:message)
	end
end

Rails/03_MusicConcertNetwork/MeetMusic/app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

    before_action :admin_only, only: [:new, :create]

    def index
        @concerts = Concert.fetch
        @today_concerts = Concert.where(date: Date.current)
 		dt = DateTime.now.end_of_month
    	@month_concerts = Concert.where(:date => Date.current.beginning_of_day..Date.current.end_of_month).order(:date)
    end

    def show
        @concert = Concert.find params[:id]
    end

    def destroy
    	@concert = Concert.find(params[:id]).try(:destroy)
    	redirect_to concerts_path, notice: "The concert of #{@concert.band} has been destroyed."
  	end

	def edit
		@concert = Concert.find(params[:id])
	end

	def new
    	@concert = Concert.new
    end

	def create
		@concert = Concert.new(concert_params)
		if Concert.find_by(band: params[:concert][:band])
			redirect_to new_concert_path, notice: 'The concert already exists. Please create a new one...'	
		elsif @concert.valid?
			@concert.save
			redirect_to concerts_path, notice: 'The concert was successfully created.'
		else
			render :new
		end
	end

	def update
		@concert = Concert.find_by(id: params[:id])
		if @concert.update_attributes(concert_params)
			redirect_to concerts_path, notice: 'Concert was successfully updated.'
		else
			render :edit
		end
	end

	private

	def concert_params
		params.require(:concert).permit(:band, :venue, :city, :date, :price, :description, :logo, comments_attributes: [:user, :message])
	end

end

Rails/03_MusicConcertNetwork/MeetMusic/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to concerts_path
    else
      redirect_to '/login'
    end
  end

  def new
    render :new
  end

  def destroy
    session.clear
    redirect_to concerts_path
  end
end

Rails/03_MusicConcertNetwork/MeetMusic/app/controllers/site_controller.rb
class SiteController < ApplicationController
    def home
        render 'home'
    end
end

Rails/03_MusicConcertNetwork/MeetMusic/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to concerts_path
    else 
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

Rails/03_MusicConcertNetwork/MeetMusic/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/03_MusicConcertNetwork/MeetMusic/app/helpers/comments_helper.rb
module CommentsHelper
end

Rails/03_MusicConcertNetwork/MeetMusic/app/helpers/concerts_helper.rb
module ConcertsHelper
end

Rails/03_MusicConcertNetwork/MeetMusic/app/helpers/sessions_helper.rb
module SessionsHelper
end

Rails/03_MusicConcertNetwork/MeetMusic/app/helpers/site_helper.rb
module SiteHelper
end

Rails/03_MusicConcertNetwork/MeetMusic/app/helpers/users_helper.rb
module UsersHelper
end

Rails/03_MusicConcertNetwork/MeetMusic/app/views/concerts/_concertform.html.erb
<%= form_for concert, :html => {:multipart => true }  do |f| %>

	<%= f.label :logo %>
	<%= f.file_field :logo %>
<br>
	<%= render 'layouts/errors', model: @concert %>
		<br>

	<div class="field">
		<%= f.label :band %>

		<br />
		<%=f.text_field :band %>
	</div>
<br>
	<div class="field">
		<%= f.label :venue %>
		<br />
		<%=f.text_field :venue %>
	</div>
<br>
	<div class="field">
		<%= f.label :city %>
		<br />
		<%=f.text_field :city %>
	</div>
<br>
	<div class="field">
		<%= f.label :date%>
		<br />
		<%=f.date_select :date %>
	</div>
<br>
	<div class="field">
		<%= f.label :price %>
		<br />
		<%=f.text_field :price %>
	</div>
<br>
	<div class="field">
		<%= f.label :description %>
		<br />
		<%=f.text_field :description %>
	</div>
<br>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>
<br>

Rails/03_MusicConcertNetwork/MeetMusic/app/views/concerts/edit.html.erb
<h2>Edit an existing Gig</h2>

<%= render 'concertform', concert: @concert %>

Rails/03_MusicConcertNetwork/MeetMusic/app/views/concerts/index.html.erb
<div class="row">
	<div class="col-md-3">
		<h2>Today's menu!!</h2>
		<ul>
		<% @today_concerts.each do |concert| %>
			<div class="media">
		  		<div class="media-left">
		    		<a href="<%= concert_path(concert) %>">
		      			<img class="media-object" src="<%= concert.logo.url(:thumb) %>" class="logo__roundedcorners" alt="Concert logo">
		    		</a>
		  		</div>
		  		<div class="media-body">
		    		<h4 class="media-heading"><%= concert.band %> in <%= concert.city %></h4>
		    		<ul>
			    		<li>Price: <%= concert.price %>€</li>
						<li><%= link_to "Click to book your ticket", concert_path(concert) %></li>
					</ul>
		  		</div>
			</div>
		<%end%>
		</ul>
	</div>
	<div class="col-md-9">
		<h2>Later this month!!</h2>
		<ul>
		<% @month_concerts.each do |concert| %>
			<div class="media">
		  		<div class="media-left">
		    		<a href="<%= concert_path(concert) %>">
		      			<img class="media-object" src="<%= concert.logo.url(:thumb) %>" class="logo__roundedcorners" alt="Concert logo">
		    		</a>
		  		</div>
		  		<div class="media-body">
		    	<h4 class="media-heading"><%= concert.band %> in <%= concert.city %> at the <%= concert.venue %></h4>
		    	<ul>
			   		<li>Price: <%= concert.price %>€</li>
					<li>More info about this gig: </li>
					<li><%= concert.description %></li>
					<li><%= link_to "Click to book your ticket", concert_path(concert) %></li>
				</ul>
		  	</div>
		</div>
	<%end%>
</div>

<div class="row">
	<div class="col-md-12">
		<h3><%= link_to "Submit your own Gig here", new_concert_path %>
		</h3>
		<h3><%= link_to "Check your most popular concerts", concerts_mostpopular_path %>
		</h3>
		<% if !@concerts.present? %>
			Currently, there are no concerts waiting for you.
			Sorry about that!
			Come back later!
		<%end%>

		<ul>
			<h4>All upcoming concerts. Click on one to see more details.</h4>
			<% @concerts.each do |concert| %>
			<li><%= link_to concert.band, concert_path(concert) %></li>
			<% end %> 
		</ul>
	</div>
</div>

Rails/03_MusicConcertNetwork/MeetMusic/app/views/concerts/new.html.erb
<h2>Submit a New Gig</h2>

<%= render 'concertform', concert: @concert %>

Rails/03_MusicConcertNetwork/MeetMusic/app/views/concerts/show.html.erb
<div class="row">
	<div class="col-md-12">
		<h1>Here are all the details about this gig </h1>
	</div>
	<div class="col-md-4">
		<ul>
			<li><%= image_tag @concert.logo.url(:medium)%></li>
			<li><%= link_to "Edit this concert", edit_concert_path  %></li> 
			<li><%= link_to 'Delete this concert', concert_path(@concert), method: :delete %></li>
			<li><h4>Leave a comment</h4></li>
			<%= form_for( :comment) do |f| %>

			<li><div class="field">
				<%= f.label :message %>
				<%=f.text_field :message %>
				</div>
			</li>
				
			<li><div class="actions">
				<%= f.submit %>
				</div>
			</li>
			<% end %>
		</ul>
	</div>
	<div class="col-md-8">
		<ul>
			<li><b><%= @concert.band %></b> will be playing at</li>
			<li><%= @concert.venue %> in <%= @concert.city %> the <%= @concert.date %></li>
		</ul>
		<ul>
			<li><b>More info about this gig:</b></li>
			<li><%= @concert.description %></li>
		</ul>
		<ul>
		<li><h3>What the users think of it...</h3></li>
		</ul>
		<ul>
			<% if @concert.comments.present? %>
				<% @concert.comments.each do |comment| %>
					<li><b><%= comment.visitor %></b> said:</li>
					<li><%= comment.message %></li>
					<li><%= link_to "Delete this comment", [@concert, comment], method: :delete %></li>
					<br>
					<%end%>
				<% else %> 
				<li>Sorry, nobody left a comment yet...</li>
			<%end%>
		</ul>
	</div>
</div>

Rails/03_MusicConcertNetwork/MeetMusic/app/views/layouts/_errors.html.erb
<% if model.errors.any? %>

	<div class="model errors">	
		<h2> 
			<%= pluralize(model.errors.count, "error") %>
			<%= "prohibited this #{model.class.name} from being saved:" %>
		</h2>

		<ul>
			<% model.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

Rails/03_MusicConcertNetwork/MeetMusic/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
 <img class="jumbotron" src="http://i.imgur.com/l9g32q6.png">
  <title>MeetMusic</title>
 
  

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
	<% if current_user.nil? %>
	<h3>Hello visitor!</h3>
		<%= link_to "Log in", '/login' %>
	<%else%> 
		<h3>Hello <%= current_user.name%> !</h3>
		<%= link_to "Log out", '/logout' %>
	<%end%>

		<% flash.each do |key, value| %>
			<%= content_tag :div, value, class: "flash-info" %>
			<% end %>

		<%= yield %>
		<footer>
			<ul>
				<li><%= link_to "All the gigs at your fingertips", concerts_path %> </li>
				<li>Powered by Rails <a href="http://bbrassart.com">@bbrassart</a> </li>
			</ul>
		</footer>
		
		</div>
	</body>
</html>

Rails/03_MusicConcertNetwork/MeetMusic/app/views/site/home.html.erb
<h1> Welcome to our Homepage </h1>

<p> IronHack powered </p> 

Rails/03_MusicConcertNetwork/MeetMusic/app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
Name: <%= f.text_field :name %><br>
Email: <%= f.text_field :email %><br>
Password: <%= f.password_field :password %><br>
Password Confirmation: <%= f.password_field :password_confirmation %>
<%= f.submit "Submit" %>
<% end %>